SELECT T.ID, T.FIRST_NAME, T.LAST_NAME, SP.EXPERIENCEYEARS,
CASE When T.PRODUCT_NAME = 'Cell Phone' THEN 'Mobiles' ELSE T.PRODUCT_NAME END AS PRODUCT_NAME,
T.ITEMS_SOLD, T.SOLD_PRICE, T.ITEMS_SOLD*T.SOLD_PRICE as TOTAL_SALES,
CASE When T.ITEMS_SOLD*T.SOLD_PRICE >= 3000 THEN 'High' WHEN T.ITEMS_SOLD*T.SOLD_PRICE >= 1500 THEN 'Medium' ELSE 'Low' END as Sales_Status,
T.SOLD_DATE, T.COUNTRY, T.REGION
FROM MYDB.ONE_DRIVE.TOTAL_SALE_IN as T
INNER JOIN
MYDB.POSTGRES_MYSCHEMA.SALESPERSONS as SP ON T.ID = SP.SALEPERSONID